Forum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    #This contains /signup and /signin urls
    path('', include('authentication.urls')),

    #This is the homepage of the website
    path('', include('questions.urls')),
    
    path('account/', include('passwords.urls')),
    path('user/', include('users.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG: 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import *

app_name = 'users'
urlpatterns = [ 
    path('<slug:slug>/<user_id>/', UserProfileView, name='view_profile'),
    path('<slug:slug>/<user_id>/edit/', EditUserProfile, name='edit_profile'),
]

users/models.py
from django.db import models

from authentication.models import *
from helpers.models import *


def get_image_filepath(self, *args, **kwargs):
	return f"profile_images/{self.pk}/{'profile_image.png'}"

def get_default_image(): 
	return 'icons/male.png' 

class UserProfile(TrackingModel): 
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_image  = models.ImageField(max_length=255, upload_to=get_image_filepath, null=True, blank=True, default=get_default_image)
    first_name = models.CharField(max_length=150, null=True)
    last_name = models.CharField(max_length=150, null=True)
    birthdate = models.DateField(null=True)
    gender = models.CharField(max_length=1, null=True)
    bio = models.TextField(null=True, blank=True, max_length=120)
    date_of_profile_update = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

users/forms.py
from django.contrib.admin.widgets import AdminDateWidget
from django import forms

from users.models import *


class UserProfileForm(forms.ModelForm):

    first_name = forms.CharField(
    max_length=150, 
    label="", 
    widget=forms.TextInput(
        attrs={
            'class': 'form-control', 
            }
        )
    )

    last_name = forms.CharField(
    max_length=150, 
    label="", 
    widget=forms.TextInput(
        attrs={
            'class': 'form-control', 
            }
        )
    )

    GENDER_CHOICES = (
    		('M', 'Male'),
    		('F', 'Female'),
     	)
    gender = forms.CharField(
        max_length=1,
        widget=forms.RadioSelect(
            choices=GENDER_CHOICES,
        )
    )

    birthdate = forms.DateField(widget=forms.SelectDateWidget)

    bio = forms.CharField(
		label="",
		widget=forms.Textarea(attrs={
			'class': 'form-control', 
			'rows': 3, 
			'placeholder': 'You can write a little about yourself...'
			})
		)

    class Meta:
        model = UserProfile
        fields = '__all__'
        exclude = ['user',]
        
    
    def save(self, commit=True):
        profile = super(UserProfileForm, self).save(commit=False)
        profile.profile_image = self.cleaned_data['profile_image']
        profile.first_name = self.cleaned_data['first_name']
        profile.last_name = self.cleaned_data['last_name']
        profile.birthdate = self.cleaned_data['birthdate']
        profile.gender = self.cleaned_data['gender']
        profile.bio = self.cleaned_data['bio']
        profile.date_of_profile_update = timezone.now()
        if commit:
            profile.save()
            return profile

# TOdo: i need to download an edit profile template so it kinda goes well with this



        

users/views.py
from django.http import HttpResponse

from django.shortcuts import render, redirect

from django.contrib import messages

from authentication.models import *
from helpers.decorators import *
from users.forms import *
from users.models import *


@redirect_unauthenticated_user_to_signin(login_url='authentication:signin')
def EditUserProfile(request, *args, **kwargs):
    #Todo: Modify the frontend of this view
    user_id = kwargs['user_id']

    try:
        profile = request.user.user_profile
    except UserProfile.DoesNotExist:
        profile = UserProfile.objects.create(user=request.user, pk=request.user.pk)
        profile.save()

    try:
        user = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        return HttpResponse('Something went wrong😥')

    if user.pk != request.user.pk:
        messages.info(request, 'What are you doing😕')
        messages.info(request, 'Try editing your own profile😏')
        return redirect('users:edit_profile', user_id=request.user.pk)


    form = UserProfileForm(instance=request.user.user_profile)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()

            destination = request.POST.get('next')
 
            if destination:
                return redirect (destination)

            return redirect('users:view_profile', user_id=request.user.pk)

    context = {
        'form': form
    }
    return render(request, 'users/edit_profile.html', context)

def UserProfileView(request, *args, **kwargs):
    user_id = kwargs['user_id']

    # try:
    #     user = User.objects.get(pk=user_id)
    # except User.DoesNotExist:
    #     return HttpResponse('Something went wrong😥')

    
    try:
        profile = UserProfile.objects.get(pk=user_id)

        if profile.first_name == 'Bot':
            if request.user.is_authenticated:
                if not request.user.is_superuser and not request.user.is_staff:
                    messages.warning(request, 'You are not authorized to view that profile🐱‍👤')
                    return redirect('users:view_profile', user_id=request.user.pk)
            else:
                messages.warning(request, 'You are not authorized to view that profile🐱‍👤')
                return redirect('questions:home')
        
    except UserProfile.DoesNotExist:
        return HttpResponse('That user does not exist!')

    context = {
        'user': profile,
    }
    return render(request, 'users/view_profile.html', context)

users/templates/users/edit_profile.html
{% extends 'base.html' %}

{% load static %}
{# load i18n admin_modify admin_media_prefix #}


{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/users/edit_profile.css' %}">
    <!-- <link rel="stylesheet" href="{# admin_media_prefix #}css/base.css">
    <link rel="stylesheet" href="{# admin_media_prefix #}css/widgets.css"> -->
{% endblock %}

<!--! I need to add django calender to my calender, the commented code is the attempt to add django admin calender. I should try adding it -->

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block navbarstylesheet %}
  <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}

{% block content %}

<form method="POST" enctype="multipart/form-data" class="p-4">
    {% csrf_token %}
    {{ form.error }}

    <div class="container">
        <!-- This is to display the warning message -->
        {% for message in messages %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                <strong>Warning!</strong> {{ message }}
              </div>
        {% endfor %} 

        <div class="row gutters">
            <!-- If the user already has a userprofile -->
            {% if request.user.user_profile.first_name != None %}
                <div class="mb-3 col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
                    <div class="card h-100">
                        <div class="card-body">
                            <div class="account-settings">
                                <div class="user-profile">
                                    <div class="user-avatar">
                                        <img src="{{ request.user.user_profile.profile_image.url }}" alt="{{ request.user.user_profile.first_name }}'s picture">
                                    </div>
                                    <h5 class="user-name text-nowrap">{{ request.user.user_profile.first_name }} {{ request.user.user_profile.last_name }}</h5>
                                    <h6 class="user-email text-nowrap">{{ request.user.email }}</h6>
                                </div>
                                <div class="bio">
                                    <h5>Bio</h5>
                                    <p>I'm {{request.user.user_profile.first_name}}. {{ request.user.user_profile.bio }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
                    <div class="card h-100">
                        <div class="card-body">
                            <div class="row gutters">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <h4 class="mb-2 text-center text-primary"><b>Personal Details</b></h4>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label for="id_first_name">First Name</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label for="id_last_name">Last Name</label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label>Gender</label>
                                        <!-- <input type="text" class="form-control" id="phone" placeholder="Enter phone number"> -->
                                        <div class="id_gender">
                                            <div>
                                                {% for gender in form.gender %}
                                                    <span class="m-2">{{ gender }}</span>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label>Birthdate</label>
                                        <div>{{ form.birthdate }}</div>

        <!-- 
                                        {# load i18n admin_modify #}
                                        {# block extrahead #}
                                            {{ block.super }}
                                            <link rel="stylesheet" href="{# admin_media_prefix #}css/base.css">
                                            <link rel="stylesheet" href="{# admin_media_prefix #}css/widgets.css">
                                            <script src="/jsi18n/"></script>
                                            <script src="{# admin_media_prefix #}js/core.js"></script>
                                            {{ form.media }}
                                        {# endblock #} -->

                                    </div>
                                </div>
                            
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="form-group mb-3">
                                        <label for="id_bio">Bio</label>
                                        {{ form.bio }}
                                    </div>
                                </div>
                            </div>

                            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                        
                            <div class="row gutters">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="text-right">
                                        <a href="{% url 'users:view_profile' request.user.slug request.user.pk %}" class="btn btn-outline-secondary">Cancel</a>
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            <!-- If the user does not have a userprofile -->
            {% elif request.user.user_profile.first_name == None %}
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="card h-100">
                        <div class="card-body">
                            <div class="row gutters">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <h4 class="mb-2 text-center text-primary"><b>Personal Details</b></h4>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label for="id_first_name">First Name</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label for="id_last_name">Last Name</label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label>Gender</label>
                                        <!-- <input type="text" class="form-control" id="phone" placeholder="Enter phone number"> -->
                                        <div class="id_gender">
                                            <div>
                                                {% for gender in form.gender %}
                                                    <span class="m-2">{{ gender }}</span>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    <div class="form-group">
                                        <label>Birthdate</label>
                                        <div>{{ form.birthdate }}</div>

        <!-- 
                                        {# load i18n admin_modify #}
                                        {# block extrahead #}
                                            {{ block.super }}
                                            <link rel="stylesheet" href="{# admin_media_prefix #}css/base.css">
                                            <link rel="stylesheet" href="{# admin_media_prefix #}css/widgets.css">
                                            <script src="/jsi18n/"></script>
                                            <script src="{# admin_media_prefix #}js/core.js"></script>
                                            {{ form.media }}
                                        {# endblock #} -->

                                    </div>
                                </div>
                            
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="form-group mb-3">
                                        <label for="id_bio">Bio</label>
                                        {{ form.bio }}
                                    </div>
                                </div>
                            </div>

                            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                        
                            <div class="row gutters">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="text-right">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

</form>








{% endblock %}


{% block script %}
    <script src="/jsi18n/"></script>
    <script src="{# admin_media_prefix #}js/core.js"></script>
{% endblock %}

users/templates/users/view_profile.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block navbar %}
	{% include 'navbar.html' %}
{% endblock %}

{% block navbarstylesheet %}
  <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/users/edit_profile.css' %}">
{% endblock %}


{% block content %}

<div class="container">
    <!-- This is to display the warning message -->
    {% for message in messages %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>Warning!</strong> {{ message }}
          </div>
    {% endfor %} 

    <div class="row gutters p-4">
        {% if user.first_name != None %}
            <div class="mb-3 col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="account-settings">
                            <div class="user-profile">
                                <div class="user-avatar">
                                    <div class="thumb-lg member-thumb mx-auto"><img src="{{ user.profile_image.url }}" class="rounded-circle img-thumbnail" alt="{{ user.first_name }}'s picture"></div>
                                </div>
                                <h5 class="user-name text-nowrap">{{ user.first_name }} {{ user.last_name }}</h5>
                                <h6 class="user-email text-nowrap">{{ user.user.email }}</h6>
                            </div>
                            <div class="bio">
                                <h5>Bio</h5>
                                <p>I'm {{ user.first_name }}; {{ user.bio }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                <h4 class="mb-2 text-center text-primary"><b>{{ user.first_name }}'s Details</b></h4>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="mt-3">
                                    <h4>{{ user.user.username }}</h4>
                                    <p class="mb-0 text-muted">Username</p>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="mt-3">
                                    <h4>{{ user.user.date_joined.date }}</h4>
                                    <p class="mb-0 text-muted">Date Joined</p>
                                </div>
                            </div>
                        </div>

                        <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                    
                     
                        <div class="mt-4">
                            <div class="row">
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                                    <div class="mt-3">
                                        <h4>{{ user.questions.count }}</h4>
                                        <p class="mb-0 text-muted">Question{{ questions | pluralize }} asked</p>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                                    <div class="mt-3">
                                        <h4>{{ user.answers_given.count }}</h4>
                                        <p class="mb-0 text-muted">Question{{ questions | pluralize }} answered</p>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                                    <div class="mt-3">
                                        <h4>{{ user.user.last_login }}</h4>
                                        <p class="mb-0 text-muted">Last login</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% elif user.first_name == None %}
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="row gutters">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                <h4 class="mb-2 text-center text-primary"><b>{{ user.user.username }}'s Details</b></h4>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="mt-3">
                                    <h4>{{ user.user.username }}</h4>
                                    <p class="mb-0 text-muted">Username</p>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                <div class="mt-3">
                                    <h4>{{ user.user.date_joined.date }}</h4>
                                    <p class="mb-0 text-muted">Date Joined</p>
                                </div>
                            </div>
                        </div>

                        <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                    
                    
                        <div class="mt-4">
                            <div class="row">
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                                    <div class="mt-3">
                                        <h4>{{ user.questions.count }}</h4>
                                        <p class="mb-0 text-muted">Question{{ questions | pluralize }} asked</p>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                                    <div class="mt-3">
                                        <h4>{{ user.answers_given.count }}</h4>
                                        <p class="mb-0 text-muted">Question{{ questions | pluralize }} answered</p>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                                    <div class="mt-3">
                                        <h4>{{ user.user.last_login }}</h4>
                                        <p class="mb-0 text-muted">Last login</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>


























{% endblock %}